project_id = "xngfyktcvkxbsvrkmpjc"

[functions.stripe-webhooks]
verify_jwt = false

[functions.create-scan]
verify_jwt = true

[functions.run-prompt]
verify_jwt = true

[functions.competitors]
verify_jwt = true

[functions.reports]
verify_jwt = true

[functions.health]
verify_jwt = false

[functions.version]
verify_jwt = false

[functions.dev-auth-me]
verify_jwt = true

[functions.admin-users]
verify_jwt = true

[functions.billing-checkout]
verify_jwt = true

[functions.limits-demo]
verify_jwt = false
