// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xngfyktcvkxbsvrkmpjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhuZ2Z5a3Rjdmt4YnN2cmttcGpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzODUzMTMsImV4cCI6MjA2OTk2MTMxM30.EKuWcTzHVKZJbZVhaXW0LEGAuzD_1XT0rVLH6qgLsqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});