name: Rollback

on:
  workflow_dispatch:
    inputs:
      deployment:
        description: "Deployment URL or ID to rollback to (e.g., vercel.app URL)"
        required: true
      environment:
        description: "preview or production"
        required: true
        default: production

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Vercel CLI
        run: npm i -g vercel@latest
      - name: Vercel Rollback
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          vercel rollback "${{ inputs.deployment }}" --token "$VERCEL_TOKEN"
          echo "Rolled back to ${{ inputs.deployment }} in ${{ inputs.environment }}"
